
-- DROP DATABASE `TRAB_CAMPEONATO`;
-- Criando o Schema do BD
CREATE SCHEMA  `TRAB_CAMPEONATO`;
USE `TRAB_CAMPEONATO`;

-- 
CREATE TABLE `ATLETA` (
    `ATLETA_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NOME` VARCHAR(50) NOT NULL,
    `ALTURA` FLOAT,
    `PESO` INT
);

CREATE TABLE `MODALIDADE` (
    `MODALIDADE_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NOME` VARCHAR(50) NOT NULL
);

CREATE TABLE `CHAVEAMENTO` (
    `CHAVEAMENTO_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `CHAVE` ENUM('Oitavas', 'Quartas', 'Semifinais', 'Finais') NOT NULL,
    `QTD_PONTOS` INT,
    `TIPO` VARCHAR(50)
);

CREATE TABLE `CLASSIFICACAO` (
    `CLASSIFICACAO_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `QTD_PONTOS` INT,
    `CHAVEAMENTO_ID` INT,
    CONSTRAINT `FK_CLASSIFICACAO_CHAVEAMENTO` FOREIGN KEY (`CHAVEAMENTO_ID`) REFERENCES `CHAVEAMENTO`(`CHAVEAMENTO_ID`)
);

CREATE TABLE `PARTIDAS` (
    `PARTIDA_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `LOCAL` VARCHAR(50),
    `DATA` DATETIME,
    `CLASSIFICACAO_ID` INT,
    CONSTRAINT `FK_PARTIDAS_CLASSIFICACAO` FOREIGN KEY (`CLASSIFICACAO_ID`) REFERENCES `CLASSIFICACAO`(`CLASSIFICACAO_ID`)
);

CREATE TABLE `EQUIPE` (
    `EQUIPE_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NOME` VARCHAR(50) NOT NULL,
    `QTD_PESSOAS` INT,
    `MODALIDADE_ID` INT,
    `ATLETA_ID` INT,
    CONSTRAINT `FK_EQUIPE_MODALIDADE` FOREIGN KEY (`MODALIDADE_ID`) REFERENCES `MODALIDADE`(`MODALIDADE_ID`),
    CONSTRAINT `FK_EQUIPE_ATLETA` FOREIGN KEY (`ATLETA_ID`) REFERENCES `ATLETA`(`ATLETA_ID`)
);

CREATE TABLE `COMPETICAO` (
    `COMPETICAO_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NOME` VARCHAR(50) NOT NULL,
    `FASE` INT,
    `TIPO_COMP` VARCHAR(50),
    `EQUIPE_ID` INT,
    `PARTIDA_ID` INT,
    CONSTRAINT `FK_COMPETICAO_EQUIPE` FOREIGN KEY (`EQUIPE_ID`) REFERENCES `EQUIPE`(`EQUIPE_ID`),
    CONSTRAINT `FK_COMPETICAO_PARTIDAS` FOREIGN KEY (`PARTIDA_ID`) REFERENCES `PARTIDAS`(`PARTIDA_ID`)
);

CREATE TABLE `RESULTADO` (
    `RESULTADO_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `EQUIPE_ID` INT,
    `PARTIDA_ID` INT,
    CONSTRAINT `FK_RESULTADO_EQUIPE` FOREIGN KEY (`EQUIPE_ID`) REFERENCES `EQUIPE`(`EQUIPE_ID`),
    CONSTRAINT `FK_RESULTADO_PARTIDAS` FOREIGN KEY (`PARTIDA_ID`) REFERENCES `PARTIDAS`(`PARTIDA_ID`)
);


